export * from './auth.services';
export * from './invoicing.services';
export * from './vtex-home.services';
export * from './vtex-products.services';
export * from './vtexauth.services';
export * from './vtexdocs.services';
export * from './vtexorder.services';
export * from './vtexShoppingCar.services';
export * from './vtexsingleorder.services';
export * from './vtex-categories.services';
export * from './vtex-search.services'
