import { themeType } from '../types/theme';

const theme: themeType = {
  fontSize: {
    'xxsmall': 11,
    'xsmall': 12.5,
    'small': 14,
    'medium': 16,
    'large': 20,
    'xlarge': 26,
    'xxlarge': 32,
    'h1': 24,
    'h2': 20,
    'h3': 18,
    'ButtonDark': 16,
    'ButtonWhite': 16,
    'h4': 16,
    'Paragraph': 15,
    'h5': 14,
    'Link': 14,
    'Placeholder': 14,
    'h6': 12,
    'Label': 12,
    'Description': 12
  },
  size: {
    'xxsmall': 10,
    'xsmall': 12,
    'small': 14,
    'medium': 16,
    'large': 18,
    'xlarge': 20,
    'xxlarge': 22,
  },
  actionButtonSize: {
    'xxsmall': 30,
    'xsmall': 40,
    'small': 50,
    'medium': 60,
    'large': 70,
    'xlarge': 80,
    'xxlarge': 90,
  },
  buttonSize: {
    'xxsmall': 8,
    'xsmall': 10,
    'small': 12,
    'medium': 14,
    'large': 16,
    'xlarge': 18,
    'xxlarge': 20,
  },
  buttonWidth: {
    'xxsmall': 100,
    'xsmall': 120,
    'small': 140,
    'medium': 160,
    'large': 180,
    'xlarge': 200,
    'xxlarge': 220,
  },
  iconSize: {
    'xxsmall': 16,
    'xsmall': 18,
    'small': 22,
    'medium': 26,
    'large': 28,
    'xlarge': 32,
    'xxlarge': 36,
  },
  avatarSize: {
    'xxsmall': 40,
    'xsmall': 60,
    'small': 80,
    'medium': 90,
    'large': 110,
    'xlarge': 120,
    'xxlarge': 140,
  },
  badgeSize: {
    'xxsmall': 10,
    'xsmall': 11,
    'small': 12,
    'medium': 13,
    'large': 14,
    'xlarge': 16,
    'xxlarge': 18,
  },
  miniBadgeSize: {
    'xxsmall': 10,
    'xsmall': 11,
    'small': 12,
    'medium': 15,
    'large': 17,
    'xlarge': 19,
    'xxlarge': 21,
  },
  listItemSpace: {
    'xxsmall': 5,
    'xsmall': 7.5,
    'small': 10,
    'medium': 12,
    'large': 14,
    'xlarge': 16,
    'xxlarge': 18,
  },
  space: {
    'none': 0,
    'xxsmall': 2.5,
    'xsmall': 5,
    'small': 7.5,
    'medium': 10,
    'large': 12.5,
    'xlarge': 15,
    'xxlarge': 20,
  },
  layoutSpace: {
    'none': 0,
    'xxsmall': 5,
    'xsmall': 10,
    'small': 12,
    'medium': 16,
    'large': 20,
    'xlarge': 24,
    'xxlarge': 32,
  },
  indicatorSize: {
    'xxsmall': 0.8,
    'xsmall': 0.9,
    'small': 1,
    'medium': 1.1,
    'large': 1.25,
    'xlarge': 1.5,
    'xxlarge': 1.7,
  },
  fontFamily: {
    'heading': 'FontAwesome',
    'text': 'FontAwesome',
  },
  textColor: {
    'dark': '#de000000',
    'dark_grey': 'darkgrey',
    'white': 'white',
    'paragraph': '#000000',
    'link': '#5fae8e',
    'medgrey': 'lightgrey',
    'grey': 'grey',
  },
  brandColor: {
    'iconn_orange_original': '#f37721',
    'iconn_green_original': '#008060',
    'iconn_red_original': '#ed2525',
    'iconn_accent_principal': '#3cb18c',
    'iconn_accent_secondary': '#faa22d',
    'iconn_warm_grey': '#f7f7f5',
    'iconn_light_grey': '#edebeb',
    'iconn_med_grey': '#dadadb',
    'iconn_grey': '#939598',
    'iconn_dark_grey': '#333333',
    'iconn_background': '#f4f4f4',
    'iconn_white': '#ffffff',
    'iconn_success': '#34c28c',
    'iconn_warning': '#f3d449',
    'iconn_error': '#cb5e69',
    'iconn_info': '#5080b2',
  },
};

export default theme;

